### ISSUE TITLE
lua runtime error

### ISSUE THREAD

**Issue by diptadas** [TimWolla/haproxy-auth-request#1]
Hi I am getting following error:

```
[ALERT] 071/113202 (13139) : parsing [haproxy.conf:2] : lua runtime error: /usr/share/haproxy/auth-request.lua:56: 'register_action' needs 3 arguments
```

I installed lua-socket using apt-get and ran the makefile. Here is my haproxy.conf file:

```
global
   lua-load /usr/share/haproxy/auth-request.lua

backend auth_request
	mode http
	server auth_request 127.0.0.1:8080 check

frontend http
	mode http
	bind *:8090
	http-request lua.auth-request auth_request     /is-allowed
	http-request deny if ! { var(txn.auth_response_successful) -m bool }
```

**Comment by diptadas** [comment]
Hello problem was with haproxy version 1.6 & 1.7. I upgraded to 1.8.4 and now it's working. Thanks.

**Comment by TimWolla** [comment]
> Hello problem was with haproxy version 1.6 & 1.7.

I verified this: Indeed the necessary APIs have only been introduced with haproxy 1.8. I am going to update the README to state this requirement, thank you.
