### ISSUE TITLE
Use ip:port instead of a backend name

### ISSUE THREAD

**Issue by jcmoraisjr** [TimWolla/haproxy-auth-request#31]
Hello Tim, I'd like to see a way to send an `ip:port` address instead of a backend to auth-request, thus avoiding to: lookup a backend + find a server + check if it's healthy, leading to a lower latency and maybe increasing the max rps. This would mostly be used to send something like `127.0.0.1:4001` which is a frontend of the same haproxy this lua script is running in. A `/path/to/socket` would also be great but afaics the current version of `haproxy-lua-http` doesn't support it.

I can implement this myself and test on my own workloads but first I want to share some approaches - maybe you have a preferable one, or another one, or maybe you have some reason you don't want to see such improvement at all =)

* Check if the input matches a pattern - eg if the input starts with `https?://`, if so we have the address, otherwise it's a backend name. This would burn a few more cpu if a backend is used;
* Create two new functions - one of them receives `ip:port`, the other one receives a backend name. This could be made in a backward compatible way, eg `auth-request-backend` and `auth-request-server`, being `auth-request` an alias to the first one;
* Create a new optional argument in the current function - faster, simpler, but I cannot see a way to implement this with a nice signature and being backward compatible at the same time.

**Comment by TimWolla** [comment]
> lookup a backend + find a server + check if it's healthy, leading to a lower latency and maybe increasing the max rps.

Is this actually an issue? Did you profile this? I honestly don't know, because I never used haproxy-auth-request at scale. I don't think I pushed it further than 10 req/s or so.

I would imagine that this lookup is completely dwarfed by the processing that goes into constructing the HTTP subrequest (e.g. catenating the HTTP headers).

**Comment by jcmoraisjr** [comment]
I'm using auth-request on a component that people expects scaling as much as any good haproxy based solution. I however must agree with you that this change should not make things much faster - there is already some overhead in the request building and response reading, making such change rather expensive compared with its benefit.

We're currently building a new cluster that should authenticate about half of the incoming requests, we should see about 70k and 100k rps based on data from a legacy environment - so at least ~30k rps should be using auth-request. This means to me that every cpu cycle we manage to drop from our solution means a VM we can drop from the haproxy cluster. I didn't profile the current configuration yet, I'll let you know as soon as I have some numbers.

I'm closing this issue since we agreed about the costs of the change doesn't cover their benefits.

**Comment by TimWolla** [comment]
> I'll let you know as soon as I have some numbers.

Perfect, thank you. I'll be happy to make / accept adjustments where required :smiley:
